version: '3.8'

services:

  main:
    image: ${LOCAL_DOCKER_IMAGE}

    environment:
        - PROJECT_NAME=${PROJECT_NAME}
        - ICUB_SIMULATION=true
        - ICUB_NAME=iCubSim
        - ICUB_USER=icub
        - ICUB_PSW=icub
        - ICUB_HOST=pc104
        - ICUB_APPS=/home/docky/workdir/apps


    command: sh -c "terminator & bash /home/docky/init.sh"
